SELECT car.CAR_ID, car.CAR_TYPE, FLOOR(car.DAILY_FEE * 30 * (100 - plan.DISCOUNT_RATE) / 100) as FEE
FROM CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN plan
ON car.CAR_TYPE = plan.CAR_TYPE
WHERE
    NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY hist
    WHERE hist.CAR_ID = car.CAR_ID
    AND hist.START_DATE <= DATE('2022-11-30')
    AND hist.END_DATE >= DATE('2022-11-01')
    )
    AND car.CAR_TYPE in ('세단', 'SUV')
    AND plan.DURATION_TYPE = '30일 이상'
    AND car.DAILY_FEE * 30 * (100 - plan.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 2000000

    
