SELECT ed2.ID AS ID, ed2.GENOTYPE AS GENOTYPE, ed1.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ed1
JOIN ECOLI_DATA AS ed2
    ON ed1.ID = ed2.PARENT_ID and ed1.GENOTYPE & ed2.GENOTYPE = ed1.GENOTYPE