SELECT DISTINCT(car.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY his
ON car.CAR_ID = his.CAR_ID
WHERE car.CAR_TYPE = '세단'
AND DATE_FORMAT(his.START_DATE, '%m') = '10'
ORDER BY CAR_ID DESC
