SELECT SUM(SCORE) AS SCORE, he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
FROM HR_DEPARTMENT AS hd
JOIN HR_EMPLOYEES AS he
JOIN HR_GRADE AS hg
    ON hd.DEPT_ID = he.DEPT_ID AND he.EMP_NO = hg.EMP_NO
WHERE hg.YEAR = 2022
GROUP BY he.EMP_NAME, he.EMP_NO, he.POSITION, he.EMAIL
ORDER BY SUM(SCORE) DESC
LIMIT 1